### ISSUE TITLE
Tidy up this 'Awesome List' (Markdown task)

### ISSUE THREAD

**Issue by raynescc** [Neuro-Hack/sponsorship#18]
Let's break the sponsors up into categories. For example:

- Food

- Swag

- Gadgets

- Money

- Venue

- Etc

Use a emoji's it will look more cool :)

**Comment by katiequin335** [comment]
What goes where?

**Comment by raynescc** [comment]
Perhaps just have a table for each category, I think I would start with;

- Swag
NameCheap
GitHub
Digital Ocean
Tech Crunch

- Food
None yet, but I will add some so make a placeholder 

- Venue
None yet, but I will add some so make a placeholder 

- Money
None yet, but I will add some so make a placeholder 

- Hardware
Estimote
Muse
Oculus
Thalmic Labs
Ultrahaptics
Leap Motion

Other
All others...
