### ISSUE TITLE
Add sponsors (Simple - Markdown task)

### ISSUE THREAD

**Issue by raynescc** [Neuro-Hack/sponsorship#23]
We're trying to create an awesome list of companies one should contact for sponsorship when organising a hackathon. You can check these hackathons and see who sponsored them for ideas..

- https://www.hacksheffield.co/

- https://astonhack.co.uk/

- http://hackkings.org/#sponsors

- https://angelhack.com/

**Add as many or as little sponsors as you like :)**

**Comment by benjamin-ross** [comment]
Any specific location (like USA only)?

**Comment by raynescc** [comment]
Nope Worldwide 👍 

Although we could create country specific categories if the sponsors are very niche :)
