### ISSUE TITLE
Make this Awesome List read.me a little more fancy! :)

### ISSUE THREAD

**Issue by raynescc** [Neuro-Hack/sponsorship#4]
Simply tidy up this Awesome List read.me a little and make it look awesome! 

Ideas:

- Add some emojis(?)

- Table (maybe) for sponsors list(?)

- Anything else you can is missing(?)

This issue will count towards the #Hacktoberfest.

p.s You can join our [Telegram Community](http://t.me/joinchat/G1fp6) here 👈

**Comment by homuncculus** [comment]
I'll give it a try

**Comment by raynescc** [comment]
Awesome! 👍
