### ISSUE TITLE
Add another potential hackathon sponsor to the awesome list

### ISSUE THREAD

**Issue by raynescc** [Neuro-Hack/sponsorship#9]

**Comment by Lahirutech** [comment]
Let me give this a try.Will you permit me to do a push request for the repo

**Comment by raynescc** [comment]
Sure just 'Fork' the repository, make your change and then submit 'pull request' with the change.
Like this: https://www.youtube.com/watch?v=YTbRzhQju4c&t=317s

**Comment by Lahirutech** [comment]
What do you mean by a potential sponser Is there any qualifications you guys prefer :) 
Thank you

**Comment by raynescc** [comment]
Mainly looking for companies that have previously sponsored a hackathon or are tech company perhaps. But no rules here really.

Cheers! :)

**Comment by raynescc** [comment]
@Lahirutech let me know if you require any help :) Looking forward to seeing your additions.

**Comment by Lahirutech** [comment]
Did I completed my first open source contribution ?? :/

**Comment by raynescc** [comment]
yup you did :)

**Comment by raynescc** [comment]
It should show your progress here: https://hacktoberfest.digitalocean.com/

**Comment by Lahirutech** [comment]
OMG Thank You Very Much for the support !!! raynescc  :)
Cheers :)

**Comment by raynescc** [comment]
Anytime :)
